name: Google Chat Notification

on:
  push:
    branches:
      - '*'

jobs:
  send_notification:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Send Google Chat message
      env:
        CHAT_WEBHOOK_URL: ${{ secrets.CHAT_WEBHOOK_URL }}
      run: |
        AUTHOR=$(git log -1 --pretty=format:'%an')
        BRANCH=$(echo ${{ github.ref }} | awk -F'/' '{print $NF}')
        curl -X POST -H 'Content-Type: application/json' -d '{
          "cards": [
            {
              "sections": [
                {
                  "widgets": [
                    {
                      "textParagraph": {
                        "text": "<b><font color=\"#4285F4\">'"$AUTHOR"'</font></b> subió cambios en la rama <b>'"$BRANCH"'</b>"
                      }
                    }
                  ]
                }
              ]
            }
          ]
        }' "$CHAT_WEBHOOK_URL"
