name: Google Chat Notification

on:
  push:
    branches:
      - '*'

jobs:
  send_notification:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Extract commit information
      run: |
        COMMIT_MESSAGE=$(git log -1 --pretty=%B)
        AUTHOR=$(git log -1 --pretty=format:'%an')
        BRANCH=$(echo ${{ github.ref }} | awk -F'/' '{print $NF}')
        
        if [[ $COMMIT_MESSAGE =~ \#([0-9]+) ]]; then
          ISSUE_NUMBER="${BASH_REMATCH[1]}"
          MESSAGE="$AUTHOR subió cambios en el issue #$ISSUE_NUMBER en la rama $BRANCH"
        else
          MESSAGE="$AUTHOR subió cambios en la rama $BRANCH"
        fi
        
        curl -X POST -H 'Content-Type: application/json' -d "{'text': '$MESSAGE'}" "$CHAT_WEBHOOK_URL"
      env:
        CHAT_WEBHOOK_URL: ${{ secrets.CHAT_WEBHOOK_URL }}
