name: Google Chat Notification

on:
  push:
    branches:
      - '*'

jobs:
  send_notification:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Send Google Chat message
      env:
        CHAT_WEBHOOK_URL: ${{ secrets.CHAT_WEBHOOK_URL }}
      run: |
        AUTHOR=$(git log -1 --pretty=format:'%an')
        BRANCH=$(echo ${{ github.ref }} | awk -F'/' '{print $NF}')
        curl -X POST -H 'Content-Type: application/json' -d "{\"text\": \"$AUTHOR subió cambios en la rama $BRANCH\"}" "$CHAT_WEBHOOK_URL"
